# Generated by Django 4.2.6 on 2024-06-20 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_logfileposition'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogEntry',
        ),
        migrations.DeleteModel(
            name='LogFilePosition',
        ),
    ]
