# Generated by Django 4.2.6 on 2024-06-26 13:06

import common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_delete_logentry_delete_logfileposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=common.models.upload_to),
        ),
    ]
