# Generated by Django 4.2.6 on 2024-06-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='file_type',
            field=models.CharField(blank=True, choices=[('Promo', 'Promotion'), ('Ardoise', 'Ardoise')], max_length=10, null=True),
        ),
    ]
