# Generated by Django 4.2.6 on 2024-04-10 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corak_API_userProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(blank=True, max_length=255, null=True)),
                ('store_address', models.CharField(blank=True, max_length=255, null=True)),
                ('store_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('corak_id', models.CharField(blank=True, max_length=100, null=True)),
                ('esl_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('zkong_public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('zkong_base_url', models.CharField(blank=True, max_length=255, null=True)),
                ('zkong_user_name', models.CharField(blank=True, max_length=30, null=True)),
                ('zkong_user_password', models.CharField(blank=True, max_length=255, null=True)),
                ('zkong_agency_id', models.CharField(blank=True, max_length=255, null=True)),
                ('zkong_merchant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('zkong_store_id', models.CharField(blank=True, max_length=255, null=True)),
                ('zkong_crypted_password', models.CharField(blank=True, max_length=255, null=True)),
                ('zkong_authorization', models.CharField(blank=True, max_length=255, null=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
