# Generated by Django 4.2.6 on 2024-06-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='corak_api_userprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
