# Generated by Django 4.2.6 on 2024-06-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user_management', '0002_corak_api_userprofile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='corak_api_userprofile',
            name='zkong_batch_delete_endpoint',
            field=models.CharField(blank=True, default='/zk/item/batchDeleteItem', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corak_api_userprofile',
            name='zkong_batch_import_endpoint',
            field=models.CharField(blank=True, default='/zk/item/batchImportItem', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='corak_api_userprofile',
            name='zkong_login_endpoint',
            field=models.CharField(blank=True, default='/zk/user/login', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='corak_api_userprofile',
            name='zkong_base_url',
            field=models.CharField(blank=True, default='https://esl-eu.zkong.com', max_length=255, null=True),
        ),
    ]
