# Generated by Django 4.2.6 on 2024-04-26 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_user_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_article', models.CharField(max_length=255, null=True)),
                ('fairTrade', models.BooleanField(default=False)),
                ('organic', models.BooleanField(default=False)),
                ('environmentallyFriendly', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_article', models.CharField(max_length=255, null=True)),
                ('libelle_cr_auto', models.CharField(blank=True, max_length=255, null=True)),
                ('libelle_lg_auto', models.CharField(blank=True, max_length=255, null=True)),
                ('geeti1_auto', models.CharField(blank=True, max_length=255, null=True)),
                ('type_auto', models.CharField(blank=True, max_length=255, null=True)),
                ('traitement_auto', models.CharField(blank=True, max_length=255, null=True)),
                ('conditionnement_auto', models.CharField(blank=True, max_length=255, null=True)),
                ('certifie_auto', models.CharField(blank=True, max_length=255, null=True)),
                ('fresh_origine_BO', models.CharField(blank=True, max_length=255, null=True)),
                ('fresh_caliber_BO', models.CharField(blank=True, max_length=255, null=True)),
                ('fresh_category_BO', models.CharField(blank=True, max_length=255, null=True)),
                ('fresh_variety_BO', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_article', models.CharField(max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('unitPriceUnit', models.CharField(choices=[('U', 'Unité'), ('K', 'Kilogramme')], max_length=1)),
                ('currency', models.CharField(max_length=5)),
                ('certificates', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_certificates', to='ardoise.certificates')),
                ('custom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_details', to='ardoise.customdetail')),
                ('store_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Product', to='custom_user_management.corak_api_userprofile')),
            ],
            options={
                'unique_together': {('code_article', 'store_profile')},
            },
        ),
        migrations.AddField(
            model_name='customdetail',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_custom', to='ardoise.product'),
        ),
        migrations.AddField(
            model_name='customdetail',
            name='store_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CustomDetail', to='custom_user_management.corak_api_userprofile'),
        ),
        migrations.AddField(
            model_name='certificates',
            name='product',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_certificates', to='ardoise.product'),
        ),
        migrations.AddField(
            model_name='certificates',
            name='store_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Certificates', to='custom_user_management.corak_api_userprofile'),
        ),
        migrations.CreateModel(
            name='Fresh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_article', models.CharField(blank=True, max_length=255, null=True)),
                ('origine_BO', models.CharField(blank=True, max_length=255, null=True)),
                ('caliber_BO', models.CharField(blank=True, max_length=255, null=True)),
                ('category_BO', models.CharField(blank=True, max_length=255, null=True)),
                ('variety_BO', models.CharField(blank=True, max_length=255, null=True)),
                ('store_profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Fresh', to='custom_user_management.corak_api_userprofile')),
            ],
            options={
                'unique_together': {('code_article', 'store_profile')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='customdetail',
            unique_together={('code_article', 'store_profile')},
        ),
        migrations.AlterUniqueTogether(
            name='certificates',
            unique_together={('code_article', 'store_profile')},
        ),
    ]
