# Generated by Django 4.2.6 on 2024-06-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardoise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdetail',
            name='lib_unit_auto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
