# Generated by Django 4.2.6 on 2024-06-03 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ardoise', '0002_customdetail_lib_unit_auto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificates',
            old_name='environmentallyFriendly',
            new_name='environmentallyFriendly',
        ),
        migrations.RenameField(
            model_name='certificates',
            old_name='fairTrade',
            new_name='fairTrade',
        ),
    ]
