# Generated by Django 4.2.6 on 2024-06-27 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ardoise', '0004_certificates_updated_at_customdetail_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customdetail',
            name='promo_gold_auto',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
